#!/bin/bash

#remove spaces
for i in *.wma; do mv "$i" `echo $i | tr ' ' '_'`; done

#Rip with Mplayer /encode with LAME
for i in *.wma; do mplayer -vo null -vc dummy -af resample=44100 -ao pcm:waveheader $i && lame -m s audiodump.wav -o "`basename "$i" .wma`.mp3"; done

rm audiodump.wav
